create extension if not exists pgcrypto;

create table if not exists public.cities (
  id integer generated by default as identity primary key,
  name text not null,
  province text not null,
  region text not null check (region in ('수도권', '경상도', '전라도', '강원도', '제주도', '충청도')),
  budget text not null check (budget in ('under100', '100to200', 'over200')),
  monthly_cost integer not null check (monthly_cost > 0),
  image_url text not null,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.city_spots (
  id integer generated by default as identity primary key,
  city_id integer not null references public.cities(id) on delete cascade,
  name text not null,
  category text not null check (category in ('카페', '코워킹', '명소')),
  description text not null,
  sort_order integer not null default 0
);

create table if not exists public.city_cost_details (
  city_id integer primary key references public.cities(id) on delete cascade,
  housing integer not null check (housing >= 0),
  food integer not null check (food >= 0),
  transport integer not null check (transport >= 0),
  etc integer not null check (etc >= 0)
);

create table if not exists public.city_environments (
  city_id integer not null references public.cities(id) on delete cascade,
  environment text not null check (environment in ('자연친화', '도심선호', '카페작업', '코워킹 필수')),
  primary key (city_id, environment)
);

create table if not exists public.city_seasons (
  city_id integer not null references public.cities(id) on delete cascade,
  season text not null check (season in ('봄', '여름', '가을', '겨울')),
  primary key (city_id, season)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  city_id integer not null references public.cities(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  content text not null check (char_length(trim(content)) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.city_likes (
  id uuid primary key default gen_random_uuid(),
  city_id integer not null references public.cities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  unique (city_id, user_id)
);

create index if not exists idx_city_spots_city_id on public.city_spots(city_id);
create index if not exists idx_reviews_city_created on public.reviews(city_id, created_at desc);
create index if not exists idx_city_likes_city_type on public.city_likes(city_id, type);
create index if not exists idx_city_likes_user_city on public.city_likes(user_id, city_id);

alter table public.cities enable row level security;
alter table public.city_spots enable row level security;
alter table public.city_cost_details enable row level security;
alter table public.city_environments enable row level security;
alter table public.city_seasons enable row level security;
alter table public.reviews enable row level security;
alter table public.city_likes enable row level security;

drop policy if exists "Public can read cities" on public.cities;
create policy "Public can read cities"
  on public.cities for select
  using (true);

drop policy if exists "Public can read city spots" on public.city_spots;
create policy "Public can read city spots"
  on public.city_spots for select
  using (true);

drop policy if exists "Public can read city costs" on public.city_cost_details;
create policy "Public can read city costs"
  on public.city_cost_details for select
  using (true);

drop policy if exists "Public can read city environments" on public.city_environments;
create policy "Public can read city environments"
  on public.city_environments for select
  using (true);

drop policy if exists "Public can read city seasons" on public.city_seasons;
create policy "Public can read city seasons"
  on public.city_seasons for select
  using (true);

drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
  on public.reviews for select
  using (true);

drop policy if exists "Users can create own reviews" on public.reviews;
create policy "Users can create own reviews"
  on public.reviews for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own reviews" on public.reviews;
create policy "Users can update own reviews"
  on public.reviews for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own reviews" on public.reviews;
create policy "Users can delete own reviews"
  on public.reviews for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Public can read city likes" on public.city_likes;
create policy "Public can read city likes"
  on public.city_likes for select
  using (true);

drop policy if exists "Users can create own city likes" on public.city_likes;
create policy "Users can create own city likes"
  on public.city_likes for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own city likes" on public.city_likes;
create policy "Users can update own city likes"
  on public.city_likes for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own city likes" on public.city_likes;
create policy "Users can delete own city likes"
  on public.city_likes for delete
  to authenticated
  using (auth.uid() = user_id);
